language: ruby
sudo: false
cache: bundler
script: bundle exec rake test:all
rvm:
  - 2.2
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby
  - jruby-head
  - rbx-3
env:
  global:
    - CODECLIMATE_REPO_TOKEN=e8d41c4e69b4127159b46a6b18a8a2b470ff001674e59c7762cce788d4021fbb
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
